// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Concreates;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Entitites.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Book"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Electronic"
                        });
                });

            modelBuilder.Entity("Entitites.Models.Product", b =>
                {
                    b.Property<int>("ProdcutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProdcutId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProdcutId = 1,
                            CategoryId = 2,
                            ProductName = "HP Laptop",
                            ProductPrice = 22000m
                        },
                        new
                        {
                            ProdcutId = 2,
                            CategoryId = 2,
                            ProductName = "PS5",
                            ProductPrice = 36000m
                        },
                        new
                        {
                            ProdcutId = 3,
                            CategoryId = 2,
                            ProductName = "Gaming Laptop",
                            ProductPrice = 32000m
                        },
                        new
                        {
                            ProdcutId = 4,
                            CategoryId = 2,
                            ProductName = "Mause",
                            ProductPrice = 2200m
                        },
                        new
                        {
                            ProdcutId = 5,
                            CategoryId = 2,
                            ProductName = "Keyboard",
                            ProductPrice = 16000m
                        },
                        new
                        {
                            ProdcutId = 6,
                            CategoryId = 1,
                            ProductName = "Ulusların Düşüşü",
                            ProductPrice = 420m
                        },
                        new
                        {
                            ProdcutId = 7,
                            CategoryId = 1,
                            ProductName = "Sistem ve Network Mühendisliği",
                            ProductPrice = 760m
                        });
                });

            modelBuilder.Entity("Entitites.Models.Product", b =>
                {
                    b.HasOne("Entitites.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entitites.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
